### ISSUE TITLE
Feature 2: User can view entries by day.

### ISSUE THREAD

**Issue by danielwrosenbaum** [danielwrosenbaum/weekly-planner#2]
## ⚙️  Feature 2

 User can view entries by day.

## 📐 Functionality

User should be able to click on any day and see everything scheduled for that day rendered in a table list. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![weeklyplanner2](https://user-images.githubusercontent.com/74999873/121938374-98ab7680-cd00-11eb-83b7-4fcccb41d3ea.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...

### ☁️ Server

- [ ] Update `server/index.js` to ...
- [x] add app.get request to get all data for each day from database
- [x] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Update component to ...
- [x] add buttons for all 7 days of week on home page
- [ ] render tables for each day
- [ ] add event handler to render table after clicking button
- [ ] add fetch request to home page to fetch data based on table
- [ ] add map function to get all data from DB to the home page

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
